name: Generate Podcast Feeds

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repo
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Step 2: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      # Step 4: Run Feed Generator
      - name: Run Feed Generator
        run: python feed.py
          
      - name: Push Repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Modified Feed"
          git push
